CREATE DATABASE IF NOT EXISTS LABORATORIO8;

CREATE TABLE IF NOT EXISTS LABORATORIO8.textos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    data VARCHAR(255) NOT NULL 
);

INSERT INTO LABORATORIO8.textos (data) VALUES ('Sistemas Distribuidos 2024');